### ISSUE TITLE
Thank you for sharing ideas

### ISSUE THREAD

**Issue by donaldpipowitch** [thejameskyle/compiler-ideas#1]
A big thank you for sharing ideas. Every now and then I try to port your super tiny compiler example to Rust when I have some spare time. Due to Rusts nature some concepts are hard to implement. I struggle a lot in the `transformer`/`traverser` phase, because of the mutability. Planning to have immutable concepts is what I currently try as well. Also trying to support _"No visitors, rely on pattern matching."_ is something which sound very helpful in my context.

Maybe get rid of _"No visiting on node "exit"."_ is something I (currently) like as well, because for now I haven't had found a need of this functionality.

So, thank you ✌️

**Comment by jamiebuilds** [comment]
Doing this immutably actually makes traversal and transformation way harder to implement as an API, it's relatively easy to use in most cases, but in some is really hard.

Immutability is a limitation on your programming, it might not be easier but it has a tendency to produce better results.
